name:                CEREScript-SS-Parser
version:             0.0.7.1
github:              "HolosDev/CEREScript-SS-Parser"
license:             OtherLicense
author:              "YongJoon Joe"
maintainer:          "Holos Works <developer@holos.dev>"
copyright:           "2020 Holos Works / PPUZZL Group"

extra-source-files:
- README.md
- ChangeLog.md

description:         Please see the README on GitHub at <https://github.com/HolosDev/CEREScript-SS-Parser#readme>

dependencies:
- base >= 4.7 && < 5
- text
- containers
- text-show
- text-show-instances
- text-trie
- vector
- CEREScript-SS

default-extensions:
- OverloadedStrings

library:
  source-dirs:
  - src

tests:
  Test-Spec:
    main:                Spec.hs
    source-dirs:
    - test
    - tests/Spec
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    default-extensions:
    - TemplateHaskell
    - OverloadedStrings
    dependencies:
    - CEREScript-SS-Parser
    - HUnit
    - QuickCheck
    - silently
    - test-framework
    - test-framework-hunit
    - test-framework-quickcheck2
    - test-framework-th
    - call-stack
