resolver: lts-14.27

packages:
- .

extra-deps:
- text-trie-0.2.5.0
- splitmix-0.0.4
- github: HolosDev/CEREScript-Core01
#- git: https://gitlab.com/holosdev/CEREScript-Core01
  commit: 36e003fd9271698652562bacbcf840e2e03698c8
