resolver: lts-14.27

packages:
- .
# In development
#- /AoDw/CEREScript/ArchCEREScript
#- /AoDw/CEREScript/CEREScript-SS00

extra-deps:
- splitmix-0.0.4
# In public
#- github: HolosDev/ArchCEREScript
#- git: https://gitlab.com/holosdev/ArchCEREScript
#  commit: 88519609a5b06a1dc7842904f1b4163fc0ca22d2
- github: HolosDev/CEREScript-SS
#- git: https://gitlab.com/holosdev/CEREScript-SS
  commit: febb13ef5712592d613f1418ed95e6d62b071962
